### ISSUE TITLE
Handling listening sessions on export boundaries

### ISSUE THREAD

**Issue by gammaw** [szkjn/lahmacun-radio-analytics#1]
Issue: say we export at midnights, then e.g. from Monday to Tuesday we may have a listener listining from 10pm on Monday over to 5 minutes past midnight on Tue and our threshold is 15mins, then we'll falsely count the guy for a valid listener for Tue too.

**Comment by gammaw** [comment]
@szkjn I did a quick scan on your last commit https://github.com/lahmacunradio/analytics/commit/248a888c2267bf17c94784304b114a3333ec5d6e on the branch https://github.com/lahmacunradio/analytics/tree/day-boundaries-fix%231 and added some inline comments. The very idea looks good (which is to check "legacy" listeners based on the time since the last export)! 

A general comment, which has nothing to do with this issue, regards to how you run `threading.Timer` to run `autoFetch()` and `autoExport()` over and over again. It seems to me that it's done recursively, which is an unnecessary complication, isn't it? I think an infinite loop would do where you call above two functions as often as required by the parameters. What do you think?

**Comment by gammaw** [comment]
@szkjn I did a quick scan on your last commit https://github.com/lahmacunradio/analytics/commit/248a888c2267bf17c94784304b114a3333ec5d6e on the branch https://github.com/lahmacunradio/analytics/tree/day-boundaries-fix%231 and added some inline comments. The very idea looks good (which is to check "legacy" listeners based on the time since the last export)! 

A general comment, which has nothing to do with this issue, regards to how you run `threading.Timer` to run `autoFetch()` and `autoExport()` over and over again. It seems to me that it's done recursively, which is an unnecessary complication, isn't it? I think an infinite loop would do where you call above two functions as often as required by the parameters. What do you think?

**Comment by gammaw** [comment]
@szkjn I might have found a bug on the following line. Isn't possible that you wrongly overwrite a previously valid (1) listener? 

https://github.com/lahmacunradio/analytics/blob/312c22b1e62c2dc2b3abdbab545713a91dc23b02/fetcher.py#L150

Also, can you check my previous comment? 

I'll add some comments to the code as some of the main logic may be tricky to read (e.g., where you create new sessions in the `monitored_data` variable).

**Comment by szkjn** [comment]
Hey @gammaw thanks for the comment. Just saw them now. Will follow up on both comments soon.

**Comment by gammaw** [comment]
High prio: 
- [ ] Check potential bug with per-user validity aggregation

Low prio:
- [ ] Review excution logic (regarding recursion)
- [ ] Review `datetime` serialisation (spec needed, potentially high prio)

@szkjn in this comment I'm collecting the todos for the first stable version.

**Comment by gammaw** [comment]
> Check potential bug with per-user validity aggregation

@szkjn FYI just checked the `lahma_2022-08-27_2200.csv` file on the server and the the long listener calc seems to be erroneous for the N/A entry.

**Comment by gammaw** [comment]
Done! https://github.com/lahmacunradio/analytics/pull/4

Grats @szkjn! 

See also: https://github.com/lahmacunradio/analytics/releases/tag/v0.1
