### ISSUE TITLE
Having sum of valid users in export file

### ISSUE THREAD

**Issue by gammaw** [szkjn/lahmacun-radio-analytics#2]
Nice feature with the validity column to mark the listeners whether or not they have listened long enough! Can you maybe sum it in the export file?

**Comment by szkjn** [comment]
Good idea, I'll push that in the next commit.

**Comment by szkjn** [comment]
This is done. One last row was added to the dataframe like so : 

ip,location,connected_time,valid
176.63.9.179,Hungary,"[[datetime.datetime(2021, 11, 19, 15, 19, 20, 314275), datetime.timedelta(seconds=4894)]]",1
95.20.249.165,Spain,"[[datetime.datetime(2021, 11, 19, 15, 58, 20, 649205), datetime.timedelta(seconds=3)]]",0
195.56.141.130,Hungary,"[[datetime.datetime(2021, 11, 19, 15, 59, 50, 843950), datetime.timedelta(seconds=1143)]]",1
Total,,,2

Feel free to have a look at the [example.csv](https://github.com/szkjn/lahmacun-radio-analytics/blob/main/example.csv) file for prettier formatting !

**Comment by gammaw** [comment]
@szkjn looks good! Thanks a lot. I'll try to deploy it asap.

**Comment by gammaw** [comment]
@szkjn what do you think of printing the number of _total_ entries too? Not what you now call total but the count of all entries in a file (3 in you example above). Cause then we would have a nice comparison for total vs "long" listeners in given time frame.

**Comment by szkjn** [comment]
@gammaw great idea! Just pushed a new version taking into account your comment. The table now ends with 2 rows 'Total listeners' + 'Total valid listeners'.
